DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS product_order CASCADE;

DROP TABLE IF EXISTS product_cart CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS carts CASCADE;

DROP TYPE user_role CASCADE;

DROP TYPE order_status CASCADE;